app_config_path: app/configs/app_config.yaml
checkpoint_path: ./checkpoints/smile.db
debug: 'false'
langchain_config:
  checkpoint_id: null
  endpoint: https://api.smith.langchain.com
  project: project-smile
  thread_id: Testing-01
  tracing_v2: 'true'
log_config:
  log_file: ''
  log_level: INFO
main_user:
  created_at: '2024-01-24T00:00:00Z'
  id: 550e8400-e29b-41d4-a716-446655440000
  main_email: elampron@gmail.com
  name: Eric
  person_details:
    address: 123 Main St, Anytown, USA
    birth_date: null
    category: Human
    email: elampron@gmail.com
    name: Eric Lampron
    notes: null
    phone: '+14155550123'
    type: Person
  person_id: null
  updated_at: null
neo4j_config:
  password: secretdb
  uri: bolt://neo4j:7687
  username: neo4j
postgres_config:
  conn: postgresql://postgres:postgres@postgres:5432/smile_checkpoints
project_info:
  project_description: "A new and improved Project-SMILES"
  project_name: Project-SMILE
  project_version: 0.1.0
