version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secretdb
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j-data/data:/data
    restart: unless-stopped