version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secretdb
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j-data/data:/data
    restart: unless-stopped
    networks:
      - smile-network
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smile_checkpoints
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - smile-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env.docker

    volumes:
      - ./backend/library:/app/library
    networks:
      - smile-network
    restart: unless-stopped

  monitoring:
    build: 
      context: ./backend
      dockerfile: Dockerfile.monitoring
    ports:
      - "8001:8001"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - smile-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "5050:80" 
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - smile-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - SMILES_API_URL=http://backend:8000
      
    depends_on:
      - backend
    networks:
      - smile-network
    restart: unless-stopped

networks:
  smile-network:
    driver: bridge

# Named volumes for persistence
volumes:
  checkpoints:
    driver: local
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local