version: '3.8'

services:
  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   platform: linux/arm64  # Specify the platform here
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - ./db/data:/var/lib/postgresql/data
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   restart: unless-stopped