services:
  livekit-smiles-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: livekit-smiles-agent
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
